vim.cmd([[highlight Normal ctermbg=NONE guibg=NONE guifg=NONE ]])
vim.cmd([[highlight NormalFloat ctermbg=NONE guibg=NONE]])
vim.cmd([[highlight SignColumn ctermbg=NONE guibg=NONE]])
vim.cmd([[highlight NvimTreeNormal guibg=NONE ctermbg=NONE]])
vim.cmd([[highlight BufferLineFill guibg=NONE ctermbg=NONE]])
vim.cmd([[highlight BufferLineBufferSelected guibg=NONE ctermbg=NONE]])
vim.cmd([[highlight TelescopeNormal guibg=NONE ctermbg=NONE]])
vim.cmd([[highlight Pmenu guibg=NONE]])
vim.cmd([[highlight CmpItemAbbrMatch guibg=NONE]])
vim.cmd([[highlight FloatShadow guibg=NONE]])
