-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd([[highlight clear]])

local highlight = function(group, bg, fg, attr)
  fg = fg and "guifg=" .. fg or ""
  bg = bg and "guibg=" .. bg or ""
  attr = attr and "gui=" .. attr or ""

  vim.api.nvim_command("highlight " .. group .. " " .. fg .. " " .. bg .. " " .. attr)
end

local link = function(target, group)
  vim.api.nvim_command("highlight! link " .. target .. " " .. group)
end

local Color8 = "#C586C0"
local Color1 = "#b5cea8"
local Color11 = "#FFFFFF"
local Color3 = "#f44747"
local Color9 = "#9CDCFE"
local Color2 = "#569cd6"
local Color4 = "#ce9178"
local Color5 = "#d4d4d4"
local Color0 = "#7ca668"
local Color7 = "#4EC9B0"
local Color6 = "#DCDCAA"
local Color10 = "#000000"
local Color12 = "#292E42"
local Color13 = "#3b426e"

highlight("Comment", nil, Color0, nil)
highlight("Number", nil, Color1, nil)
highlight("TSCharacter", nil, Color2, nil)
highlight("Error", nil, Color3, nil)
highlight("Type", nil, Color2, nil)
highlight("String", nil, Color4, nil)
highlight("Keyword", nil, Color2, nil)
highlight("Conditional", nil, Color2, nil)
highlight("Repeat", nil, Color2, nil)
highlight("Operator", nil, Color5, nil)
highlight("Function", nil, Color6, nil)
highlight("Type", nil, Color7, nil)
highlight("Conditional", nil, Color8, nil)
highlight("Repeat", nil, Color8, nil)
highlight("Identifier", nil, Color9, nil)
highlight("WildMenu", Color10, Color11, nil)
highlight("Pmenu", Color10, Color11, nil)
highlight("PmenuSel", Color12, nil, nil)
highlight("PmenuThumb", Color10, Color11, nil)
highlight("Normal", Color10, Color11, nil)
highlight("Visual", Color13, nil, nil)
highlight("CursorLine", Color12, nil, nil)
highlight("ColorColumn", Color12, nil, nil)
highlight("SignColumn", Color10, nil, nil)
highlight("TSPunctDelimiter", nil, Color11, nil)

link("TelescopeNormal", "Normal")
link("TSField", "Constant")
link("Macro", "Function")
link("TSFuncMacro", "Macro")
link("Whitespace", "Comment")
link("TSTag", "MyTag")
link("TSNamespace", "TSType")
link("CursorLineNr", "Identifier")
link("TSKeyword", "Keyword")
link("Operator", "Keyword")
link("TSProperty", "TSField")
link("TSNumber", "Number")
link("Folded", "Comment")
link("TSConstBuiltin", "TSVariableBuiltin")
link("TSConditional", "Conditional")
link("TSLabel", "Type")
link("TSFunction", "Function")
link("TSFloat", "Number")
link("TSParameter", "Constant")
link("TSPunctBracket", "MyTag")
link("TSOperator", "Operator")
link("TSParameterReference", "TSParameter")
link("TSRepeat", "Repeat")
link("Conditional", "Operator")
link("TSType", "Type")
link("TSConstant", "Constant")
link("TSComment", "Comment")
link("NonText", "Comment")
link("TSTagDelimiter", "Type")
link("TSString", "String")
link("Repeat", "Conditional")
link("TSPunctSpecial", "TSPunctDelimiter")
